### ISSUE TITLE
De-duplication doesn't change data on Dashboard

### ISSUE THREAD

**Issue by CCoffie** [OWASP/django-DefectDojo#169]
So it looks like when DefectDojo marks a finding as a duplicate it doesn't reflect those changes on the dashboard stats.

**Comment by aaronweaver** [comment]
@CCoffie Is Dojo marking findings as duplicate when you upload via the API? I was just testing this out and I don't see findings marked as a duplicate.

**Comment by CCoffie** [comment]
Yeah I think you're right. I thought It was working earlier. It looks like things aren't marked duplicate if they are marked verified or active. In the API I default to both verified and active to True. That might have something to do with it.

**Comment by grendel513** [comment]
@CCoffie, @aaronweaver  - if by dashboards you mean anything in the /metics views they are cached for 5 minutes.  you can add a param, for example ?a=1, to bust the cache.  However, they have to be a duplicate for them to have an effect on the metrics views.

**Comment by devGregA** [comment]
Hi @CCoffie @grendel513 and all I don't think this is an issue because the dashboard graphs or 'historic information' e.g. what was found. Not what is active. It would be nice for this to be configurable, but with how Dojo currently is I don't think this is a bug. The other metrics pages have the active information.
