### ISSUE TITLE
Update Django Version to 1.11 LTS

### ISSUE THREAD

**Issue by devGregA** [OWASP/django-DefectDojo#250]
### Make sure you assign this issue to yourself so folks do not duplicate effort.

Currently DefectDojo uses Django 1.8(LTS). Update all setup files necessary to make Dojo compatible with the new LTS version of Django (1.11). This includes but is not limited to setup.py and manage.py. All CI tests must pass and all supported install options must work.

**Comment by mish24** [comment]
@devGregA  Can I take this up? :)

**Comment by devGregA** [comment]
Awesome! You got it.

**Comment by mish24** [comment]
On it! @devGregA

**Comment by mish24** [comment]
![screenshot from 2017-04-16 21-19-18](https://cloud.githubusercontent.com/assets/24610197/25072388/6bc66810-22ea-11e7-8f29-abd0e38a64c2.png)
https://dev.mysql.com/doc/relnotes/connector-python/en/news-2-1-3.html
@devGregA  Heya! So, it seems like MySQL support for later versions of Ubuntu and Django 1.9 hasn't been added yet. I would say we must use PostgreSQL for further upgrades. What are your thoughts?

**Comment by devGregA** [comment]
Thank you for working on this @mish24 :). Shoot. Some of the metrics used preloaded sql for efficiency https://github.com/OWASP/django-DefectDojo/blob/master/dojo/metrics/views.py#L85, @aaronweaver @grendel513. Can I get your thoughts here please?

**Comment by mish24** [comment]
@devGregA  Are you sure all the metrics use preloaded SQL? Because if that was the case, the tables would be created you know. I'll try to explain step by step
1. The first error comes due to old version of django-filter. After upgradation, I get the error `AppRegistryNotReady: The apps aren't loaded yet`.
2. Just to delve deeper, I try to fix this issue somehow, and the next error is `ProgrammingError : 1146 Table databas_nam.django_finding' doesn't exist`.
3. Again to delve deeper, I change the filters and models a bit to see if the error is related to Django or the database, I tweak the values a bit, and then it gives a `1113 A table must have at least one column`.
Now, this means that somewhere in the code we're not allowing null values to be added to the table, which breaks the entire thing. Overall, this must be database error itself, related to `Finding` model.
I guess I'll try more to see how I can get through this

**Comment by devGregA** [comment]
Hi @mish24, only the larger queries are preloaded. For 1. I've seen that before. for some reason django isn't setup in that call. I **believe** I've fixed that before by changing manage.py. 2. Sounds like the DB schema isn't in place. Try `python manage.py syncdb`. 3. sounds similar to 2. I think syncdb will also resolve this issue.

Hope this helps!

**Comment by mish24** [comment]
@devGregA  For 1.9 we'll have `makemigrations` and `migrate`. I'll retry the entire process and see where it takes me.

Thanks!
