### ISSUE TITLE
Newest version on docker hub

### ISSUE THREAD

**Issue by bartosznaumowicz-olx** [OWASP/django-DefectDojo#322]
Hello,
when are you planing to deploy newest version of DD on Docker hub? I believe docker hub serves old one.

Regards
OLX team

**Comment by devGregA** [comment]
Hi @bartosznaumowicz-olx, unfortunately our primary docker resource hasn't had much availability. 
Right now the top priorities for the maintainers are: 1. Fixing the bugs introduced from upgrading to Django 1.11 (in progress) 2. Migrating our CI tests from Docker to Ansible (not started) 3. Switching our API to use Django Rest instead of Tastypie (not started)

Sorry :( I wish I had better news. I will leave this open for tracking though so at some point it will be prioritized.

**Comment by devGregA** [comment]
@bartosznaumowicz-olx new image is done, need to update the docs https://github.com/OWASP/django-DefectDojo/blob/master/Dockerfile

**Comment by devGregA** [comment]
Fixed via https://github.com/OWASP/django-DefectDojo/pull/412 @bartosznaumowicz-olx
