### ISSUE TITLE
Jira Integration

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#66]
Automated integration of findings with Jira to reduce the manual effort of copying and pasting findings from two systems.

**Comment by devGregA** [comment]
This one has been on our radar for a while. We kicked around using the API versus using the web-hooks, and ultimately decided API was probably the way to go for configuration simplicity. The next thought is when should it poll? Concurrency if the finding is being edited in both at the same time? I guess that would be the advantage of using the web-hook and the API, but I worry about the added complexity. Mapping from JIRA to Dojo since JIRA is highly configurable and uses custom fields?

I think that at least for the mapping this probably should be managed in settings and we let the admin define what should map to what (Dojo.field to Jira.field).

**Comment by davevs** [comment]
IMHO Jira integration should work both ways. In Jira, teams can create sprints (in scrum) which can be mapped to engagements in ddojo. When issues are added in ddojo there should be a possibility to push them to jira as issues.

**Comment by devGregA** [comment]
@davevs @aaronweaver  will have this pushed by Friday.
