### ISSUE TITLE
Bulk Edit of Findings

### ISSUE THREAD

**Issue by aaronweaver** [OWASP/django-DefectDojo#98]
I'd like to be able to bulk edit findings in the Product >> Findings view. That way it will be much faster when vetting findings. Should be able to change severity, verified and active.

**Comment by grendel513** [comment]
Hey @aaronweaver - do you mean from this page (http://127.0.0.1:8000/product/1/findings):
<img width="1428" alt="screen shot 2016-10-30 at 7 11 11 pm" src="https://cloud.githubusercontent.com/assets/233694/19841193/d907fd0c-9ed4-11e6-80b4-58b739ebe62e.png">

Or would it be more appropriate from the test page (http://127.0.0.1:8000/test/50) where the findings are listed:
<img width="1411" alt="screen shot 2016-10-30 at 7 11 38 pm" src="https://cloud.githubusercontent.com/assets/233694/19841196/fb057092-9ed4-11e6-91cc-284dadd26a6d.png">

I think Test Finding listing is more appropriate since we are already have the option to edit on that page.  The Product Finding listing page does not have edit capabilities, and it may be confusing to add this feature there.

Thoughts?

**Comment by aaronweaver** [comment]
@grendel513 Agree, the test page makes the most sense as that is where most will be editing the findings.

**Comment by grendel513** [comment]
@aaronweaver - pull request submitted.  It will add bulk update as follows:

<img width="1316" alt="screen shot 2016-10-31 at 2 12 24 pm" src="https://cloud.githubusercontent.com/assets/233694/19868027/49096024-9f74-11e6-9fa1-5ff4ec4ed802.png">

<img width="1326" alt="screen shot 2016-10-31 at 2 12 33 pm" src="https://cloud.githubusercontent.com/assets/233694/19868029/4efa7a72-9f74-11e6-82da-2d87e742dd22.png">

<img width="1328" alt="screen shot 2016-10-31 at 2 12 46 pm" src="https://cloud.githubusercontent.com/assets/233694/19868035/547ee406-9f74-11e6-81e6-f129280813e7.png">

<img width="1320" alt="screen shot 2016-10-31 at 2 12 59 pm" src="https://cloud.githubusercontent.com/assets/233694/19868039/59686460-9f74-11e6-9d64-9c9a55e4c847.png">
